import { VocabWord } from '../hooks/useVocabEngine';

export const barron800: VocabWord[] = [
    { "word": "abate", "meaning": "become less in amount or intensity" },
    { "word": "abdicate", "meaning": "give up power, duties, or obligations" },
    { "word": "aberrant", "meaning": "markedly different from an accepted norm" },
    { "word": "abeyance", "meaning": "temporary cessation or suspension" },
    { "word": "abject", "meaning": "of the most contemptible kind" },
    { "word": "abjure", "meaning": "formally reject or disavow a formerly held belief" },
    { "word": "abscission", "meaning": "the act of cutting something off" },
    { "word": "abscond", "meaning": "run away, often taking something or somebody along" },
    { "word": "abstemious", "meaning": "marked by temperance in indulgence" },
    { "word": "abstinence", "meaning": "the trait of refraining from something, especially alcohol" },
    { "word": "abysmal", "meaning": "exceptionally bad or displeasing" },
    { "word": "accretion", "meaning": "an increase by natural growth or addition" },
    { "word": "accrue", "meaning": "grow by addition" },
    { "word": "adamant", "meaning": "very hard native crystalline carbon valued as a gem" },
    { "word": "adjunct", "meaning": "something added to another thing but not essential to it" },
    { "word": "admonish", "meaning": "scold or reprimand; take to task" },
    { "word": "adulterate", "meaning": "make impure by adding a foreign or inferior substance" },
    { "word": "aesthetic", "meaning": "characterized by an appreciation of beauty or good taste" },
    { "word": "affected", "meaning": "influenced" },
    { "word": "affinity", "meaning": "a natural attraction or feeling of kinship" },
    { "word": "aggrandize", "meaning": "embellish; increase the scope, power, or importance of" },
    { "word": "aggregate", "meaning": "a sum total of many heterogeneous things taken together" },
    { "word": "alacrity", "meaning": "liveliness and eagerness" },
    { "word": "alchemy", "meaning": "a pseudoscientific forerunner of chemistry in medieval times" },
    { "word": "allay", "meaning": "lessen the intensity of or calm" },
    { "word": "alleviate", "meaning": "provide physical relief, as from pain" },
    { "word": "alloy", "meaning": "a mixture containing two or more metallic elements" },
    { "word": "allure", "meaning": "the power to entice or attract" },
    { "word": "amalgamate", "meaning": "bring or combine together or with something else" },
    { "word": "ambiguous", "meaning": "having more than one possible meaning" },
    { "word": "ambivalence", "meaning": "mixed feelings or emotions" },
    { "word": "ambrosia", "meaning": "the food and drink of the gods" },
    { "word": "ameliorate", "meaning": "make better" },
    { "word": "amenable", "meaning": "disposed or willing to comply" },
    { "word": "amenity", "meaning": "something that provides value, pleasure, or convenience" },
    { "word": "amulet", "meaning": "a trinket thought to be a magical protection against evil" },
    { "word": "anachronism", "meaning": "locating something at a time when it couldn't have existed" },
    { "word": "analgesic", "meaning": "capable of relieving pain" },
    { "word": "analogous", "meaning": "similar or equivalent in some respects" },
    { "word": "anarchy", "meaning": "a state of lawlessness and disorder" },
    { "word": "anodyne", "meaning": "capable of relieving pain" },
    { "word": "anomalous", "meaning": "deviating from the general or common order or type" },
    { "word": "anomie", "meaning": "lack of moral standards in a society" },
    { "word": "antecedent", "meaning": "a preceding occurrence or cause or event" },
    { "word": "antediluvian", "meaning": "of or relating to the period before the biblical flood" },
    { "word": "antipathy", "meaning": "a feeling of intense dislike" },
    { "word": "apathy", "meaning": "an absence of emotion or enthusiasm" },
    { "word": "apex", "meaning": "the highest point of something" },
    { "word": "apogee", "meaning": "the farthest point in an orbit around the Earth" },
    { "word": "apothegm", "meaning": "a short pithy instructive saying" },
    { "word": "appease", "meaning": "make peace with" },
    { "word": "appellation", "meaning": "identifying words by which someone or something is called" },
    { "word": "apposite", "meaning": "being of striking appropriateness and pertinence" },
    { "word": "apprise", "meaning": "inform somebody of something" },
    { "word": "approbation", "meaning": "official acceptance or agreement" },
    { "word": "appropriate", "meaning": "suitable for a particular person, place, or situation" },
    { "word": "apropos", "meaning": "of a suitable, fitting, or pertinent nature" },
    { "word": "arabesque", "meaning": "position in which the dancer has one leg raised behind" },
    { "word": "archeology", "meaning": "the branch of anthropology that studies prehistoric people and their cultures" },
    { "word": "ardor", "meaning": "feelings of great warmth and intensity" },
    { "word": "arduous", "meaning": "characterized by effort to the point of exhaustion" },
    { "word": "argot", "meaning": "a characteristic language of a particular group" },
    { "word": "arrest", "meaning": "take into custody" },
    { "word": "artifact", "meaning": "a man-made object" },
    { "word": "artless", "meaning": "simple and natural; without cunning or deceit" },
    { "word": "ascetic", "meaning": "someone who practices self denial as a spiritual discipline" },
    { "word": "asperity", "meaning": "harshness of manner" },
    { "word": "aspersion", "meaning": "a disparaging remark" },
    { "word": "assiduous", "meaning": "marked by care and persistent effort" },
    { "word": "assuage", "meaning": "provide physical relief, as from pain" },
    { "word": "astringent", "meaning": "tending to draw together or constrict soft organic tissue" },
    { "word": "asylum", "meaning": "a shelter from danger or hardship" },
    { "word": "atavism", "meaning": "a reappearance of an earlier characteristic" },
    { "word": "attenuate", "meaning": "become weaker, in strength, value, or magnitude" },
    { "word": "audacious", "meaning": "disposed to venture or take risks" },
    { "word": "austere", "meaning": "of a stern or strict bearing or demeanor" },
    { "word": "autonomous", "meaning": "existing as an independent entity" },
    { "word": "avarice", "meaning": "reprehensible acquisitiveness; insatiable desire for wealth" },
    { "word": "aver", "meaning": "declare or affirm solemnly and formally as true" },
    { "word": "avocation", "meaning": "an auxiliary activity" },
    { "word": "avuncular", "meaning": "being or relating to an uncle" },
    { "word": "axiomatic", "meaning": "evident without proof or argument" },
    { "word": "bacchanalian", "meaning": "used of riotously drunken merrymaking" },
    { "word": "banal", "meaning": "repeated too often; overfamiliar through overuse" },
    { "word": "banter", "meaning": "light teasing repartee" },
    { "word": "bard", "meaning": "a lyric poet" },
    { "word": "bawdy", "meaning": "humorously vulgar" },
    { "word": "beatify", "meaning": "make blessedly happy" },
    { "word": "bedizen", "meaning": "decorate tastelessly" },
    { "word": "behemoth", "meaning": "someone or something that is abnormally large and powerful" },
    { "word": "belie", "meaning": "be in contradiction with" },
    { "word": "beneficent", "meaning": "doing or producing good" },
    { "word": "bifurcate", "meaning": "split or divide into two" },
    { "word": "bionics", "meaning": "application of biological principles to engineering systems" },
    { "word": "blandishment", "meaning": "flattery intended to persuade" },
    { "word": "blase", "meaning": "nonchalantly unconcerned" },
    { "word": "bolster", "meaning": "support and strengthen" },
    { "word": "bombastic", "meaning": "ostentatiously lofty in style" },
    { "word": "boorish", "meaning": "ill-mannered and coarse in behavior or appearance" },
    { "word": "bovine", "meaning": "any of various wild or domestic cattle" },
    { "word": "brazen", "meaning": "not held back by conventional ideas of behavior" },
    { "word": "broach", "meaning": "bring up a topic for discussion" },
    { "word": "bucolic", "meaning": "devoted to raising sheep or cattle" },
    { "word": "burgeon", "meaning": "grow and flourish" },
    { "word": "burnish", "meaning": "polish and make shiny" },
    { "word": "buttress", "meaning": "a support usually of stone or brick" },
    { "word": "cacophonous", "meaning": "having an unpleasant sound" },
    { "word": "cadge", "meaning": "obtain or seek to obtain by wheedling" },
    { "word": "callous", "meaning": "emotionally hardened" },
    { "word": "calumny", "meaning": "a false accusation of an offense" },
    { "word": "canard", "meaning": "a deliberately misleading fabrication" },
    { "word": "canon", "meaning": "a collection of books accepted as holy scripture" },
    { "word": "cant", "meaning": "a slope in the turn of a road or track" },
    { "word": "cantankerous", "meaning": "stubbornly obstructive and unwilling to cooperate" },
    { "word": "capricious", "meaning": "determined by chance or impulse rather than by necessity" },
    { "word": "captious", "meaning": "tending to find and call attention to faults" },
    { "word": "cardinal", "meaning": "a vivid red color" },
    { "word": "carnal", "meaning": "of or relating to the body or flesh" },
    { "word": "carping", "meaning": "persistent petty and unjustified criticism" },
    { "word": "cartography", "meaning": "the making of maps and charts" },
    { "word": "caste", "meaning": "a hereditary social class among Hindus" },
    { "word": "castigation", "meaning": "verbal punishment" },
    { "word": "cataclysm", "meaning": "a sudden violent change in the earth's surface" },
    { "word": "catalyst", "meaning": "substance that initiates or accelerates a chemical reaction" },
    { "word": "categorical", "meaning": "relating to or included in a class or classes" },
    { "word": "caucus", "meaning": "meet to select a candidate or promote a policy" },
    { "word": "causal", "meaning": "involving an entity that produces an effect" },
    { "word": "caustic", "meaning": "capable of destroying or eating away by chemical action" },
    { "word": "celestial", "meaning": "relating to or inhabiting a divine heaven" },
    { "word": "centrifugal", "meaning": "tending to move away from the middle" },
    { "word": "centripetal", "meaning": "tending to move toward an area in the middle" },
    { "word": "champion", "meaning": "someone who has won first place in a competition" },
    { "word": "chasten", "meaning": "censure severely" },
    { "word": "chicanery", "meaning": "the use of tricks to deceive someone" },
    { "word": "chivalry", "meaning": "the medieval principles governing knightly conduct" },
    { "word": "churlish", "meaning": "having a bad disposition; surly" },
    { "word": "circuitous", "meaning": "deviating from a straight course" },
    { "word": "clairvoyant", "meaning": "someone who can perceive things not present to the senses" },
    { "word": "clamor", "meaning": "utter or proclaim insistently and noisily" },
    { "word": "clique", "meaning": "an exclusive circle of people with a common purpose" },
    { "word": "cloister", "meaning": "residence that is a place of religious seclusion" },
    { "word": "coagulate", "meaning": "change from a liquid to a thickened or solid state" },
    { "word": "coalesce", "meaning": "fuse or cause to come together" },
    { "word": "coda", "meaning": "the closing section of a musical composition" },
    { "word": "codify", "meaning": "organize into a system, such as a body of law" },
    { "word": "cognizant", "meaning": "having or showing knowledge or understanding or realization" },
    { "word": "collage", "meaning": "a paste-up of pieces to form an artistic image" },
    { "word": "commensurate", "meaning": "corresponding in size or degree or extent" },
    { "word": "compendium", "meaning": "a publication containing a variety of works" },
    { "word": "complacent", "meaning": "contented to a fault with oneself or one's actions" },
    { "word": "complaisant", "meaning": "showing a cheerful willingness to do favors for others" },
    { "word": "complement", "meaning": "something added to embellish or make perfect" },
    { "word": "compliant", "meaning": "disposed to act in accordance with someone's wishes" },
    { "word": "compunction", "meaning": "a feeling of deep regret, usually for some misdeed" },
    { "word": "concave", "meaning": "curving inward" },
    { "word": "conciliatory", "meaning": "making or willing to make concessions" },
    { "word": "concoct", "meaning": "make something by mixing" },
    { "word": "concomitant", "meaning": "following or accompanying as a consequence" },
    { "word": "condone", "meaning": "excuse, overlook, or make allowances for" },
    { "word": "confound", "meaning": "be confusing or perplexing to" },
    { "word": "congenial", "meaning": "suitable to your needs" },
    { "word": "conjugal", "meaning": "relating to the relationship between a wife and husband" },
    { "word": "connoisseur", "meaning": "an expert able to appreciate a field" },
    { "word": "conscript", "meaning": "enroll into service compulsorily" },
    { "word": "consecrate", "meaning": "give entirely to a specific person, activity, or cause" },
    { "word": "contend", "meaning": "compete for something" },
    { "word": "contentious", "meaning": "showing an inclination to disagree" },
    { "word": "contiguous", "meaning": "having a common boundary or edge" },
    { "word": "continence", "meaning": "voluntary control over urinary and fecal discharge" },
    { "word": "contrite", "meaning": "feeling or expressing pain or sorrow" },
    { "word": "contumacious", "meaning": "willfully obstinate; stubbornly disobedient" },
    { "word": "conundrum", "meaning": "a difficult problem" },
    { "word": "convention", "meaning": "the act of meeting formally" },
    { "word": "converge", "meaning": "be adjacent or come together" },
    { "word": "convex", "meaning": "curving or bulging outward" },
    { "word": "convivial", "meaning": "occupied with or fond of the pleasures of good company" },
    { "word": "convoluted", "meaning": "highly complex or intricate" },
    { "word": "copious", "meaning": "large in number or quantity" },
    { "word": "coquette", "meaning": "talk or behave amorously, without serious intentions" },
    { "word": "cornucopia", "meaning": "a horn filled with fruit and grain symbolizing prosperity" },
    { "word": "cosmology", "meaning": "metaphysical study of the origin and nature of the universe" },
    { "word": "covert", "meaning": "secret or hidden" },
    { "word": "covetous", "meaning": "immoderately desirous of acquiring something" },
    { "word": "cozen", "meaning": "be dishonest with" },
    { "word": "craven", "meaning": "lacking even the rudiments of courage; abjectly fearful" },
    { "word": "credence", "meaning": "the mental attitude that something is believable" },
    { "word": "credo", "meaning": "any system of principles or beliefs" },
    { "word": "daunt", "meaning": "cause to lose courage" },
    { "word": "dearth", "meaning": "an insufficient quantity or number" },
    { "word": "debauchery", "meaning": "a wild gathering" },
    { "word": "decorum", "meaning": "propriety in manners and conduct" },
    { "word": "de facto", "meaning": "existing, whether with lawful authority or not" },
    { "word": "defame", "meaning": "charge falsely or with malicious intent" },
    { "word": "default", "meaning": "an option that is selected automatically" },
    { "word": "defer", "meaning": "yield to another's wish or opinion" },
    { "word": "deference", "meaning": "courteous regard for people's feelings" },
    { "word": "defunct", "meaning": "no longer in force or use; inactive" },
    { "word": "delineate", "meaning": "represented accurately or precisely" },
    { "word": "demographic", "meaning": "a statistic characterizing human populations" },
    { "word": "demotic", "meaning": "of or for the common people" },
    { "word": "demur", "meaning": "politely refuse or take exception to" },
    { "word": "denigrate", "meaning": "attack the good name and reputation of someone" },
    { "word": "denizen", "meaning": "a plant or animal naturalized in a region" },
    { "word": "denouement", "meaning": "the outcome of a complex sequence of events" },
    { "word": "deride", "meaning": "treat or speak of with contempt" },
    { "word": "derivative", "meaning": "a compound obtained from another compound" },
    { "word": "desiccate", "meaning": "lacking vitality or spirit; lifeless" },
    { "word": "desuetude", "meaning": "a state of inactivity or disuse" },
    { "word": "desultory", "meaning": "marked by lack of definite plan, purpose, or enthusiasm" },
    { "word": "deterrent", "meaning": "something immaterial that interferes with action or progress" },
    { "word": "detraction", "meaning": "a petty disparagement" },
    { "word": "deviant", "meaning": "a person whose behavior does not conform to social norms" },
    { "word": "diaphanous", "meaning": "so thin as to transmit light" },
    { "word": "diatribe", "meaning": "thunderous verbal attack" },
    { "word": "dichotomy", "meaning": "a classification into two opposed parts or subclasses" },
    { "word": "diffidence", "meaning": "lack of self-assurance" },
    { "word": "diffuse", "meaning": "spread out; not concentrated in one place" },
    { "word": "digression", "meaning": "a message that departs from the main subject" },
    { "word": "dirge", "meaning": "a song or hymn of mourning as a memorial to a dead person" },
    { "word": "disabuse", "meaning": "free somebody from an erroneous belief" },
    { "word": "discern", "meaning": "perceive, recognize, or detect" },
    { "word": "discerning", "meaning": "having or revealing keen insight and good judgment" },
    { "word": "discomfit", "meaning": "cause to lose one's composure" },
    { "word": "discordant", "meaning": "not in agreement or harmony" },
    { "word": "discredit", "meaning": "the state of being held in low esteem" },
    { "word": "discrepancy", "meaning": "a difference between conflicting facts or claims or opinions" },
    { "word": "discrete", "meaning": "constituting a separate entity or part" },
    { "word": "discretion", "meaning": "power of making choices unconstrained by external agencies" },
    { "word": "disingenuous", "meaning": "not straightforward or candid" },
    { "word": "disinterested", "meaning": "unaffected by concern for one's own welfare" },
    { "word": "disjointed", "meaning": "taken apart at the points of connection" },
    { "word": "dismiss", "meaning": "stop associating with" },
    { "word": "disparage", "meaning": "express a negative opinion of" },
    { "word": "disparate", "meaning": "fundamentally different or distinct in quality or kind" },
    { "word": "dissemble", "meaning": "behave unnaturally or affectedly" },
    { "word": "disseminate", "meaning": "cause to become widely known" },
    { "word": "dissident", "meaning": "a person who objects to some established policy" },
    { "word": "dissolution", "meaning": "separation into component parts" },
    { "word": "dissonance", "meaning": "disagreeable sounds" },
    { "word": "distend", "meaning": "cause to expand as if by internal pressure" },
    { "word": "distill", "meaning": "undergo condensation" },
    { "word": "distrait", "meaning": "having the attention diverted especially because of anxiety" },
    { "word": "diverge", "meaning": "move or draw apart" },
    { "word": "divest", "meaning": "take away possessions from someone" },
    { "word": "divulge", "meaning": "make known to the public information previously kept secret" },
    { "word": "doctrinaire", "meaning": "a stubborn person of arbitrary or arrogant opinions" },
    { "word": "document", "meaning": "a representation of a person's thinking with symbolic marks" },
    { "word": "doggerel", "meaning": "a comic verse of irregular measure" },
    { "word": "dogmatic", "meaning": "pertaining to a code of beliefs accepted as authoritative" },
    { "word": "dormant", "meaning": "inactive but capable of becoming active" },
    { "word": "dross", "meaning": "worthless or dangerous material that should be removed" },
    { "word": "dupe", "meaning": "fool or hoax" },
    { "word": "ebullient", "meaning": "joyously unrestrained" },
    { "word": "eclectic", "meaning": "selecting what seems best of various styles or ideas" },
    { "word": "effervescence", "meaning": "the process of bubbling as gas escapes" },
    { "word": "effete", "meaning": "excessively self-indulgent, affected, or decadent" },
    { "word": "efficacy", "meaning": "capacity or power to produce a desired result" },
    { "word": "effrontery", "meaning": "audacious behavior that you have no right to" },
    { "word": "egoism", "meaning": "concern for your own interests and welfare" },
    { "word": "egotistical", "meaning": "having an inflated idea of one's own importance" },
    { "word": "elegy", "meaning": "a mournful poem; a lament for the dead" },
    { "word": "elicit", "meaning": "call forth, as an emotion, feeling, or response" },
    { "word": "elixir", "meaning": "a substance believed to cure all ills" },
    { "word": "elysian", "meaning": "relating to the abode of the blessed after death" },
    { "word": "emaciated", "meaning": "very thin, especially from disease or hunger or cold" },
    { "word": "embellish", "meaning": "make more attractive, as by adding ornament or color" },
    { "word": "emollient", "meaning": "a substance with a soothing effect when applied to the skin" },
    { "word": "empirical", "meaning": "derived from experiment and observation rather than theory" },
    { "word": "emulate", "meaning": "strive to equal or match, especially by imitating" },
    { "word": "encomium", "meaning": "a formal expression of praise" },
    { "word": "endemic", "meaning": "native to or confined to a certain region" },
    { "word": "enervate", "meaning": "weaken physically, mentally, or morally" },
    { "word": "engender", "meaning": "call forth" },
    { "word": "enhance", "meaning": "increase" },
    { "word": "entomology", "meaning": "the branch of zoology that studies insects" },
    { "word": "enunciate", "meaning": "express or state clearly" },
    { "word": "ephemeral", "meaning": "anything short-lived, as an insect that lives only for a day" },
    { "word": "epistemology", "meaning": "the philosophical theory of knowledge" },
    { "word": "equable", "meaning": "not varying" },
    { "word": "equanimity", "meaning": "steadiness of mind under stress" },
    { "word": "equitable", "meaning": "fair to all parties as dictated by reason and conscience" },
    { "word": "equivocation", "meaning": "intentional vagueness or ambiguity" },
    { "word": "errant", "meaning": "straying from the right course or from accepted standards" },
    { "word": "erudite", "meaning": "having or showing profound knowledge" },
    { "word": "esoteric", "meaning": "understandable only by an enlightened inner circle" },
    { "word": "essay", "meaning": "an analytic or interpretive literary composition" },
    { "word": "estimable", "meaning": "deserving of respect or high regard" },
    { "word": "ethnocentric", "meaning": "centered on a specific ethnic group, usually one's own" },
    { "word": "etiology", "meaning": "the cause of a disease" },
    { "word": "etymology", "meaning": "a history of a word" },
    { "word": "eugenics", "meaning": "the promotion of controlled breeding in human populations" },
    { "word": "eulogy", "meaning": "a formal expression of praise for someone who has died" },
    { "word": "euphemism", "meaning": "an inoffensive expression substituted for an offensive one" },
    { "word": "euphoria", "meaning": "a feeling of great elation" },
    { "word": "euthanasia", "meaning": "the act of killing someone painlessly" },
    { "word": "evince", "meaning": "give expression to" },
    { "word": "evocative", "meaning": "serving to bring to mind" },
    { "word": "exacerbate", "meaning": "make worse" },
    { "word": "exact", "meaning": "marked by strict and complete accordance with fact" },
    { "word": "exculpate", "meaning": "pronounce not guilty of criminal charges" },
    { "word": "execrable", "meaning": "unequivocally detestable" },
    { "word": "exhort", "meaning": "spur on or encourage especially by cheers and shouts" },
    { "word": "exigency", "meaning": "a pressing or urgent situation" },
    { "word": "existential", "meaning": "relating to or dealing with the state of being" },
    { "word": "exorcise", "meaning": "expel through adjuration or prayers" },
    { "word": "expatiate", "meaning": "add details to clarify an idea" },
    { "word": "expatriate", "meaning": "a person who is voluntarily absent from home or country" },
    { "word": "expiate", "meaning": "make amends for" },
    { "word": "explicate", "meaning": "elaborate, as of theories and hypotheses" },
    { "word": "expository", "meaning": "serving to expound or set forth" },
    { "word": "extant", "meaning": "still in existence; not extinct or destroyed or lost" },
    { "word": "extemporaneous", "meaning": "with little or no preparation or forethought" },
    { "word": "extirpate", "meaning": "destroy completely, as if down to the roots" },
    { "word": "extraneous", "meaning": "not belonging to that in which it is contained" },
    { "word": "extrapolation", "meaning": "an inference about the future based on known facts" },
    { "word": "extrinsic", "meaning": "not forming an essential part of a thing" },
    { "word": "facetious", "meaning": "cleverly amusing in tone" },
    { "word": "facilitate", "meaning": "make easier" },
    { "word": "factotum", "meaning": "a servant employed to do a variety of jobs" },
    { "word": "fallacious", "meaning": "containing or based on incorrect reasoning" },
    { "word": "fallow", "meaning": "left unplowed and unseeded during a growing season" },
    { "word": "fatuous", "meaning": "devoid of intelligence" },
    { "word": "fauna", "meaning": "all the animal life in a particular region or period" },
    { "word": "fawning", "meaning": "attempting to win favor by flattery" },
    { "word": "felicitous", "meaning": "exhibiting an agreeably appropriate manner or style" },
    { "word": "feral", "meaning": "wild and menacing" },
    { "word": "fervor", "meaning": "feelings of great warmth and intensity" },
    { "word": "fetid", "meaning": "offensively malodorous" },
    { "word": "fetter", "meaning": "a shackle for the ankles or feet" },
    { "word": "fiat", "meaning": "a legally binding command or decision" },
    { "word": "fidelity", "meaning": "the quality of being faithful" },
    { "word": "filibuster", "meaning": "a tactic for delaying legislation by making long speeches" },
    { "word": "finesse", "meaning": "subtly skillful handling of a situation" },
    { "word": "fissure", "meaning": "a long narrow depression in a surface" },
    { "word": "flag", "meaning": "a rectangular piece of cloth of distinctive design" },
    { "word": "fledgling", "meaning": "young bird that has just become capable of flying" },
    { "word": "flora", "meaning": "all the plant life in a particular region or period" },
    { "word": "florid", "meaning": "elaborately or excessively ornamented" },
    { "word": "flourish", "meaning": "grow vigorously" },
    { "word": "flout", "meaning": "treat with contemptuous disregard" },
    { "word": "flux", "meaning": "a state of constant change" },
    { "word": "foment", "meaning": "try to stir up" },
    { "word": "forbearance", "meaning": "a delay in enforcing rights or claims or privileges" },
    { "word": "forestall", "meaning": "keep from happening or arising; make impossible" },
    { "word": "formidable", "meaning": "extremely impressive in strength or excellence" },
    { "word": "forswear", "meaning": "formally reject or disavow" },
    { "word": "founder", "meaning": "a person who establishes some institution" },
    { "word": "fracas", "meaning": "a noisy quarrel" },
    { "word": "fractious", "meaning": "easily irritated or annoyed" },
    { "word": "fresco", "meaning": "a mural done with watercolors on wet plaster" },
    { "word": "frieze", "meaning": "an ornament consisting of a horizontal sculptured band" },
    { "word": "froward", "meaning": "habitually disposed to disobedience and opposition" },
    { "word": "frugality", "meaning": "prudence in avoiding waste" },
    { "word": "fulminate", "meaning": "cause to explode violently and with loud noise" },
    { "word": "fulsome", "meaning": "unpleasantly and excessively suave or ingratiating" },
    { "word": "fusion", "meaning": "the act of melding or melting together" },
    { "word": "futile", "meaning": "producing no result or effect" },
    { "word": "gainsay", "meaning": "take exception to" },
    { "word": "gambol", "meaning": "play or run boisterously" },
    { "word": "garrulous", "meaning": "full of trivial conversation" },
    { "word": "gauche", "meaning": "lacking social poise or refinement" },
    { "word": "geniality", "meaning": "a disposition to be friendly and approachable" },
    { "word": "gerrymander", "meaning": "divide voting districts unfairly and to one's advantage" },
    { "word": "glib", "meaning": "artfully persuasive in speech" },
    { "word": "goad", "meaning": "stab or urge on as if with a pointed stick" },
    { "word": "gossamer", "meaning": "a gauze fabric with an extremely fine texture" },
    { "word": "gouge", "meaning": "an impression in a surface, as made by a blow" },
    { "word": "grandiloquent", "meaning": "lofty in style" },
    { "word": "gregarious", "meaning": "temperamentally seeking and enjoying the company of others" },
    { "word": "grouse", "meaning": "popular game bird having a plump body and feathered legs" },
    { "word": "guile", "meaning": "shrewdness as demonstrated by being skilled in deception" },
    { "word": "guileless", "meaning": "innocent and free of deceit" },
    { "word": "guise", "meaning": "an artful or simulated semblance" },
    { "word": "gullible", "meaning": "naive and easily deceived or tricked" },
    { "word": "gustatory", "meaning": "of or relating to the sense of taste" },
    { "word": "halcyon", "meaning": "a mythical bird said to breed at the winter solstice" },
    { "word": "hallowed", "meaning": "worthy of religious veneration" },
    { "word": "harangue", "meaning": "a loud bombastic declamation expressed with strong emotion" },
    { "word": "harrowing", "meaning": "causing extreme distress" },
    { "word": "herbivorous", "meaning": "feeding only on plants" },
    { "word": "hermetic", "meaning": "completely sealed or airtight" },
    { "word": "heterodox", "meaning": "characterized by departure from accepted standards" },
    { "word": "heuristic", "meaning": "a commonsense rule to help solve some problem" },
    { "word": "hieroglyph", "meaning": "a symbol in a pictorial writing system" },
    { "word": "hirsute", "meaning": "having or covered with hair" },
    { "word": "histrionic", "meaning": "overly dramatic or emotional" },
    { "word": "homeostasis", "meaning": "metabolic equilibrium maintained by biological mechanisms" },
    { "word": "homily", "meaning": "a sermon on a moral or religious topic" },
    { "word": "homogeneous", "meaning": "all of the same or similar kind or nature" },
    { "word": "hyperbole", "meaning": "extravagant exaggeration" },
    { "word": "iconoclastic", "meaning": "characterized by attack on established beliefs" },
    { "word": "idolatry", "meaning": "the worship of objects or images as gods" },
    { "word": "igneous", "meaning": "produced by the action of fire or intense heat" },
    { "word": "imbroglio", "meaning": "an intricate and confusing interpersonal situation" },
    { "word": "immutable", "meaning": "not subject or susceptible to change or variation" },
    { "word": "impair", "meaning": "make worse or less effective" },
    { "word": "impassive", "meaning": "having or revealing little emotion or sensibility" },
    { "word": "impecunious", "meaning": "not having enough money to pay for necessities" },
    { "word": "impede", "meaning": "be a hindrance or obstacle to" },
    { "word": "impermeable", "meaning": "preventing especially liquids to pass or diffuse through" },
    { "word": "imperturbable", "meaning": "marked by extreme calm and composure" },
    { "word": "impervious", "meaning": "not admitting of passage or capable of being affected" },
    { "word": "impinge", "meaning": "infringe upon" },
    { "word": "implacable", "meaning": "incapable of being appeased or pacified" },
    { "word": "implausible", "meaning": "highly imaginative but unlikely" },
    { "word": "implicit", "meaning": "suggested though not directly expressed" },
    { "word": "implode", "meaning": "burst inward" },
    { "word": "imprecation", "meaning": "the act of calling down a curse that invokes evil" },
    { "word": "impute", "meaning": "attribute or credit to" },
    { "word": "inadvertently", "meaning": "without knowledge or intention" },
    { "word": "incarnate", "meaning": "possessing or existing in bodily form" },
    { "word": "inchoate", "meaning": "only partly in existence; imperfectly formed" },
    { "word": "incongruity", "meaning": "the quality of disagreeing" },
    { "word": "inconsequential", "meaning": "lacking worth or importance" },
    { "word": "incorporate", "meaning": "make into a whole or make part of a whole" },
    { "word": "incursion", "meaning": "the act of entering some territory or domain" },
    { "word": "indeterminate", "meaning": "not fixed or known in advance" },
    { "word": "indigence", "meaning": "a state of extreme poverty or destitution" },
    { "word": "indolent", "meaning": "disinclined to work or exertion" },
    { "word": "ineluctable", "meaning": "impossible to avoid or evade" },
    { "word": "inert", "meaning": "unable to move or resist motion" },
    { "word": "inertia", "meaning": "the tendency of something to stay in rest or motion" },
    { "word": "ingenuous", "meaning": "lacking in sophistication or worldliness" },
    { "word": "inherent", "meaning": "existing as an essential constituent or characteristic" },
    { "word": "innocuous", "meaning": "not injurious to physical or mental health" },
    { "word": "insensible", "meaning": "barely able to be perceived" },
    { "word": "insinuate", "meaning": "suggest in an indirect or covert way; give to understand" },
    { "word": "insipid", "meaning": "lacking interest or significance or impact" },
    { "word": "insouciant", "meaning": "marked by unconcern" },
    { "word": "insularity", "meaning": "lack of openness to new ideas; narrow-mindedness" },
    { "word": "insuperable", "meaning": "incapable of being surpassed or excelled" },
    { "word": "intangible", "meaning": "incapable of being perceived by the senses, especially touch" },
    { "word": "interdict", "meaning": "command against" },
    { "word": "internecine", "meaning": "within a group or organization" },
    { "word": "interpolate", "meaning": "insert words into texts, often falsifying it thereby" },
    { "word": "interregnum", "meaning": "the time between two reigns or governments" },
    { "word": "intimate", "meaning": "marked by close acquaintance, association, or familiarity" },
    { "word": "intractable", "meaning": "difficult to manage or mold" },
    { "word": "intransigence", "meaning": "stubborn refusal to compromise or change" },
    { "word": "introspective", "meaning": "given to examining own sensory and perceptual experiences" },
    { "word": "inundate", "meaning": "fill or cover completely, usually with water" },
    { "word": "inured", "meaning": "made tough by habitual exposure" },
    { "word": "invective", "meaning": "abusive language used to express blame or censure" },
    { "word": "inveigh", "meaning": "complain bitterly" },
    { "word": "inveigle", "meaning": "influence or urge by gentle urging, caressing, or flattering" },
    { "word": "inveterate", "meaning": "habitual" },
    { "word": "invidious", "meaning": "containing or implying a slight or showing prejudice" },
    { "word": "irascible", "meaning": "quickly aroused to anger" },
    { "word": "irresolute", "meaning": "uncertain how to act or proceed" },
    { "word": "itinerant", "meaning": "traveling from place to place to work" },
    { "word": "itinerary", "meaning": "an established line of travel or access" },
    { "word": "jaundiced", "meaning": "affected by yellowing of the skin" },
    { "word": "jibe", "meaning": "shift from one side of the ship to the other" },
    { "word": "jocose", "meaning": "characterized by jokes and good humor" },
    { "word": "juggernaut", "meaning": "a massive inexorable force" },
    { "word": "junta", "meaning": "a group of officers who rule a country after seizing power" },
    { "word": "juxtapose", "meaning": "place side by side" },
    { "word": "kudos", "meaning": "an expression of approval and commendation" },
    { "word": "labile", "meaning": "liable to change" },
    { "word": "laconic", "meaning": "brief and to the point" },
    { "word": "lambaste", "meaning": "censure severely or angrily" },
    { "word": "lascivious", "meaning": "driven by lust" },
    { "word": "lassitude", "meaning": "a feeling of lack of interest or energy" },
    { "word": "latent", "meaning": "potentially existing but not presently evident or realized" },
    { "word": "laud", "meaning": "praise, glorify, or honor" },
    { "word": "lethargic", "meaning": "deficient in alertness or activity" },
    { "word": "levee", "meaning": "an embankment built to prevent a river from overflowing" },
    { "word": "levity", "meaning": "a manner lacking seriousness" },
    { "word": "liberal", "meaning": "showing or characterized by broad-mindedness" },
    { "word": "libertine", "meaning": "unrestrained by convention or morality" },
    { "word": "libido", "meaning": "a Freudian term for sexual urge or desire" },
    { "word": "lilliputian", "meaning": "very small" },
    { "word": "limn", "meaning": "make a portrait of" },
    { "word": "limpid", "meaning": "clear and bright" },
    { "word": "linguistic", "meaning": "consisting of or related to language" },
    { "word": "litany", "meaning": "a prayer consisting of a series of invocations by the priest" },
    { "word": "literati", "meaning": "well-educated people who are interested in books" },
    { "word": "litigation", "meaning": "a legal proceeding in a court" },
    { "word": "log", "meaning": "a segment of the trunk of a tree" },
    { "word": "loquacious", "meaning": "full of trivial conversation" },
    { "word": "lucid", "meaning": "transparently clear; easily understandable" },
    { "word": "lucre", "meaning": "informal terms for money" },
    { "word": "luminous", "meaning": "softly bright or radiant" },
    { "word": "lustrous", "meaning": "reflecting light" },
    { "word": "Machiavellian", "meaning": "of or relating to amoral or conniving political principles" },
    { "word": "machination", "meaning": "a crafty and involved plot to achieve your ends" },
    { "word": "maelstrom", "meaning": "a powerful circular current of water" },
    { "word": "magnanimity", "meaning": "nobility and generosity of spirit" },
    { "word": "malign", "meaning": "speak unfavorably about" },
    { "word": "malinger", "meaning": "avoid responsibilities and duties, often by faking illness" },
    { "word": "malleable", "meaning": "capable of being shaped or bent" },
    { "word": "maverick", "meaning": "someone who exhibits independence in thought and action" },
    { "word": "megalomania", "meaning": "a psychological state characterized by delusions of grandeur" },
    { "word": "menagerie", "meaning": "a collection of live animals for study or display" },
    { "word": "mendacious", "meaning": "given to lying" },
    { "word": "mendicant", "meaning": "a pauper who lives by begging" },
    { "word": "meretricious", "meaning": "tastelessly showy" },
    { "word": "mesmerize", "meaning": "attract strongly, as if with a magnet" },
    { "word": "metamorphosis", "meaning": "striking change in appearance or character or circumstances" },
    { "word": "metaphysics", "meaning": "the philosophical study of being and knowing" },
    { "word": "meteorological", "meaning": "relating to atmospheric events, especially the weather" },
    { "word": "meticulous", "meaning": "marked by precise accordance with details" },
    { "word": "mettle", "meaning": "the courage to carry on" },
    { "word": "mettlesome", "meaning": "having a proud, courageous, and unbroken spirit" },
    { "word": "microcosm", "meaning": "a miniature model of something" },
    { "word": "militate", "meaning": "have force or influence; bring about an effect or change" },
    { "word": "minatory", "meaning": "threatening or foreshadowing evil or tragic developments" },
    { "word": "minuscule", "meaning": "very small" },
    { "word": "minutia", "meaning": "a small or minor detail" },
    { "word": "misanthrope", "meaning": "someone who dislikes people in general" },
    { "word": "miscellany", "meaning": "a collection containing a variety of sorts of things" },
    { "word": "miscreant", "meaning": "a person without moral scruples" },
    { "word": "misogynist", "meaning": "a misanthrope who dislikes women in particular" },
    { "word": "mitigate", "meaning": "lessen or to try to lessen the seriousness or extent of" },
    { "word": "mnemonic", "meaning": "of or relating to the practice of aiding the memory" },
    { "word": "modicum", "meaning": "a small or moderate or token amount" },
    { "word": "mollify", "meaning": "cause to be more favorably inclined" },
    { "word": "monolithic", "meaning": "imposing in size or bulk or solidity" },
    { "word": "morose", "meaning": "showing a brooding ill humor" },
    { "word": "motley", "meaning": "consisting of a haphazard assortment of different kinds" },
    { "word": "multifarious", "meaning": "having many aspects" },
    { "word": "mundane", "meaning": "found in the ordinary course of events" },
    { "word": "necromancy", "meaning": "conjuring up the dead, especially for prophesying" },
    { "word": "negate", "meaning": "make ineffective by counterbalancing the effect of" },
    { "word": "neologism", "meaning": "a newly invented word or phrase" },
    { "word": "neophyte", "meaning": "a participant with no experience with an activity" },
    { "word": "nexus", "meaning": "the means of connection between things linked in series" },
    { "word": "nonplussed", "meaning": "filled with bewilderment" },
    { "word": "nostalgia", "meaning": "a longing for something past" },
    { "word": "nostrum", "meaning": "patent medicine whose efficacy is questionable" },
    { "word": "nugatory", "meaning": "of no real value" },
    { "word": "obdurate", "meaning": "stubbornly persistent in wrongdoing" },
    { "word": "obsequious", "meaning": "attempting to win favor from influential people by flattery" },
    { "word": "obviate", "meaning": "do away with" },
    { "word": "occlude", "meaning": "block passage through" },
    { "word": "occult", "meaning": "supernatural forces and events and beings collectively" },
    { "word": "odyssey", "meaning": "a long wandering and eventful journey" },
    { "word": "officious", "meaning": "intrusive in a meddling or offensive manner" },
    { "word": "olfactory", "meaning": "of or relating to the sense of smell" },
    { "word": "oligarchy", "meaning": "a political system governed by a few people" },
    { "word": "onerous", "meaning": "burdensome or difficult to endure" },
    { "word": "onomatopoeia", "meaning": "using words that imitate the sound they denote" },
    { "word": "opprobrium", "meaning": "a state of extreme dishonor" },
    { "word": "ornithologist", "meaning": "a zoologist who studies feathered animals" },
    { "word": "oscillate", "meaning": "move or swing from side to side regularly" },
    { "word": "ostentatious", "meaning": "intended to attract notice and impress others" },
    { "word": "overweening", "meaning": "presumptuously arrogant" },
    { "word": "paean", "meaning": "a hymn of praise" },
    { "word": "paleontology", "meaning": "the earth science that studies fossil organisms" },
    { "word": "pallid", "meaning": "pale, as of a person's complexion" },
    { "word": "panegyric", "meaning": "formally expressing praise" },
    { "word": "paragon", "meaning": "a perfect embodiment of a concept" },
    { "word": "partisan", "meaning": "a fervent and even militant proponent of something" },
    { "word": "pathological", "meaning": "relating to the study of diseases" },
    { "word": "pathos", "meaning": "a quality that arouses emotions, especially pity or sorrow" },
    { "word": "patois", "meaning": "a regional dialect of a language" },
    { "word": "paucity", "meaning": "an insufficient quantity or number" },
    { "word": "pedant", "meaning": "a person who is preoccupied with rules and learning" },
    { "word": "pedantic", "meaning": "marked by a narrow focus on or display of learning" },
    { "word": "pellucid", "meaning": "transmitting light; able to be seen through with clarity" },
    { "word": "penchant", "meaning": "a strong liking or preference" },
    { "word": "penury", "meaning": "a state of extreme poverty or destitution" },
    { "word": "peregrination", "meaning": "traveling or wandering around" },
    { "word": "peremptory", "meaning": "putting an end to all debate or action" },
    { "word": "perennial", "meaning": "lasting an indefinitely long time" },
    { "word": "perfidious", "meaning": "tending to betray" },
    { "word": "perfunctory", "meaning": "hasty and without attention to detail" },
    { "word": "perigee", "meaning": "the nearest point in an orbit around the Earth" },
    { "word": "permeable", "meaning": "allowing fluids or gases to pass or diffuse through" },
    { "word": "perturb", "meaning": "disturb in mind or make uneasy" },
    { "word": "pervasive", "meaning": "spreading or spread throughout" },
    { "word": "petulant", "meaning": "easily irritated or annoyed" },
    { "word": "phlegmatic", "meaning": "showing little emotion" },
    { "word": "phoenix", "meaning": "a legendary bird reborn from ashes" },
    { "word": "physiognomy", "meaning": "the human face" },
    { "word": "piety", "meaning": "righteousness by virtue of being religiously devout" },
    { "word": "piquant", "meaning": "having an agreeably pungent taste" },
    { "word": "pique", "meaning": "call forth, as an emotion, feeling, or response" },
    { "word": "placate", "meaning": "cause to be more favorably inclined" },
    { "word": "placid", "meaning": "calm and free from disturbance" },
    { "word": "plaintive", "meaning": "expressing sorrow" },
    { "word": "plasticity", "meaning": "the property of being physically malleable" },
    { "word": "platitude", "meaning": "a trite or obvious remark" },
    { "word": "platonic", "meaning": "free from physical desire" },
    { "word": "plethora", "meaning": "extreme excess" },
    { "word": "plumb", "meaning": "exactly vertical" },
    { "word": "plume", "meaning": "the feather of a bird" },
    { "word": "plummet", "meaning": "drop sharply" },
    { "word": "plutocracy", "meaning": "a political system governed by the wealthy" },
    { "word": "porous", "meaning": "full of holes" },
    { "word": "poseur", "meaning": "a person who habitually pretends to be something he is not" },
    { "word": "pragmatic", "meaning": "concerned with practical matters" },
    { "word": "prate", "meaning": "speak about unimportant matters rapidly and incessantly" },
    { "word": "prattle", "meaning": "speak about unimportant matters rapidly and incessantly" },
    { "word": "preamble", "meaning": "a preliminary introduction" },
    { "word": "precarious", "meaning": "not secure; beset with difficulties" },
    { "word": "precept", "meaning": "a rule of personal conduct" },
    { "word": "precipitate", "meaning": "bring about abruptly" },
    { "word": "precursor", "meaning": "something indicating the approach of something or someone" },
    { "word": "preempt", "meaning": "acquire for oneself before others can do so" },
    { "word": "prehensile", "meaning": "adapted for grasping" },
    { "word": "premonition", "meaning": "an early warning about a future event" },
    { "word": "presage", "meaning": "a foreboding about what is about to happen" },
    { "word": "presumptuous", "meaning": "going beyond what is appropriate" },
    { "word": "preternatural", "meaning": "existing outside of or not in accordance with nature" },
    { "word": "prevaricate", "meaning": "be deliberately ambiguous or unclear" },
    { "word": "primordial", "meaning": "having existed from the beginning" },
    { "word": "pristine", "meaning": "immaculately clean and unused" },
    { "word": "probity", "meaning": "complete and confirmed integrity" },
    { "word": "problematic", "meaning": "making great mental demands" },
    { "word": "prodigal", "meaning": "recklessly wasteful" },
    { "word": "profound", "meaning": "situated at or extending to great depth" },
    { "word": "prohibitive", "meaning": "tending to discourage, especially of prices" },
    { "word": "proliferate", "meaning": "grow rapidly" },
    { "word": "propensity", "meaning": "a natural inclination" },
    { "word": "propitiate", "meaning": "make peace with" },
    { "word": "propriety", "meaning": "correct behavior" },
    { "word": "proscribe", "meaning": "command against" },
    { "word": "provident", "meaning": "giving something useful for the future" },
    { "word": "puissant", "meaning": "powerful" },
    { "word": "punctilious", "meaning": "marked by precise accordance with details" },
    { "word": "pungent", "meaning": "strong and sharp to the sense of taste or smell" },
    { "word": "purport", "meaning": "have the often misleading appearance of being or intending" },
    { "word": "pusillanimous", "meaning": "lacking in courage, strength, and resolution" },
    { "word": "quagmire", "meaning": "a soft wet area of land that sinks underfoot" },
    { "word": "quail", "meaning": "a small game bird" },
    { "word": "qualified", "meaning": "meeting the proper standards and requirements" },
    { "word": "qualm", "meaning": "uneasiness about the fitness of an action" },
    { "word": "query", "meaning": "an instance of questioning" },
    { "word": "quibble", "meaning": "evade the truth by raising irrelevant objections" },
    { "word": "quiescent", "meaning": "being quiet or still or inactive" },
    { "word": "quorum", "meaning": "gathering of minimal number of members" },
    { "word": "raconteur", "meaning": "a person skilled in telling anecdotes" },
    { "word": "rail", "meaning": "a horizontal bar" },
    { "word": "raiment", "meaning": "especially fine or decorative clothing" },
    { "word": "ramification", "meaning": "a consequence, especially one causing complications" },
    { "word": "rarefied", "meaning": "of high moral or intellectual value" },
    { "word": "rationale", "meaning": "an explanation of the fundamental reasons" },
    { "word": "rebus", "meaning": "a puzzle consisting of pictures representing words" },
    { "word": "recalcitrant", "meaning": "stubbornly resistant to authority or control" },
    { "word": "recant", "meaning": "formally reject a formerly held belief" },
    { "word": "recluse", "meaning": "one who lives in solitude" },
    { "word": "recondite", "meaning": "difficult to understand" },
    { "word": "redoubtable", "meaning": "inspiring fear" },
    { "word": "reductionist", "meaning": "explaining complex theories in simpler terms" },
    { "word": "refract", "meaning": "change in direction of a propagating wave" },
    { "word": "refractory", "meaning": "stubbornly resistant to authority or control" },
    { "word": "refulgent", "meaning": "radiating or as if radiating light" },
    { "word": "refute", "meaning": "overthrow by argument or evidence" },
    { "word": "regale", "meaning": "entertain in an agreeable fashion" },
    { "word": "relegate", "meaning": "assign to a lower position" },
    { "word": "remonstrate", "meaning": "argue in protest or opposition" },
    { "word": "renege", "meaning": "fail to fulfill a promise or obligation" },
    { "word": "reparation", "meaning": "something done in expiation of a wrong" },
    { "word": "repine", "meaning": "express discontent" },
    { "word": "reprise", "meaning": "a repetition of a musical passage" },
    { "word": "reproach", "meaning": "express criticism towards" },
    { "word": "reprobate", "meaning": "a person without moral scruples" },
    { "word": "repudiate", "meaning": "refuse to acknowledge as valid" },
    { "word": "rescind", "meaning": "cancel officially" },
    { "word": "resolution", "meaning": "a decision to do something" },
    { "word": "resolve", "meaning": "find a solution or answer" },
    { "word": "reticent", "meaning": "reluctant to draw attention to yourself" },
    { "word": "reverent", "meaning": "feeling or showing profound respect" },
    { "word": "riposte", "meaning": "a counterattack made immediately after parrying" },
    { "word": "rococo", "meaning": "having excessive asymmetrical ornamentation" },
    { "word": "rubric", "meaning": "category name" },
    { "word": "rue", "meaning": "feel sorry for; be contrite about" },
    { "word": "ruse", "meaning": "a deceptive maneuver" },
    { "word": "sage", "meaning": "a mentor in spiritual topics" },
    { "word": "salacious", "meaning": "suggestive of moral looseness" },
    { "word": "salubrious", "meaning": "promoting health" },
    { "word": "salutary", "meaning": "tending to promote physical well-being" },
    { "word": "sanction", "meaning": "official permission or approval" },
    { "word": "sardonic", "meaning": "disdainfully or ironically humorous" },
    { "word": "sartorial", "meaning": "of or relating to tailoring or clothing" },
    { "word": "satiate", "meaning": "fill to satisfaction" },
    { "word": "saturate", "meaning": "infuse or fill completely" },
    { "word": "saturnine", "meaning": "bitter or scornful" },
    { "word": "satyr", "meaning": "one of a class of woodland deities" },
    { "word": "savor", "meaning": "a particular taste or smell" },
    { "word": "schematic", "meaning": "represented in simplified form" },
    { "word": "secrete", "meaning": "generate and separate from cells" },
    { "word": "sedition", "meaning": "illegal action inciting resistance" },
    { "word": "sedulous", "meaning": "marked by care and persistent effort" },
    { "word": "seismic", "meaning": "caused by an earthquake" },
    { "word": "sensual", "meaning": "marked by the appetites of the body" },
    { "word": "sensuous", "meaning": "providing perceptible pleasure" },
    { "word": "sentient", "meaning": "endowed with feeling" },
    { "word": "servile", "meaning": "submissive or fawning" },
    { "word": "sextant", "meaning": "instrument for measuring angular distance" },
    { "word": "shard", "meaning": "a broken piece of a brittle artifact" },
    { "word": "sidereal", "meaning": "of or relating to the stars" },
    { "word": "simian", "meaning": "relating to an ape or monkey" },
    { "word": "simile", "meaning": "figure of speech expressing resemblance" },
    { "word": "sinecure", "meaning": "a job that involves minimal duties" },
    { "word": "singular", "meaning": "being a single and separate thing" },
    { "word": "sinuous", "meaning": "curved or curving in and out" },
    { "word": "skeptic", "meaning": "someone who habitually doubts beliefs" },
    { "word": "sobriety", "meaning": "state of being unaffected by alcohol" },
    { "word": "sodden", "meaning": "wet through and through" },
    { "word": "solicitous", "meaning": "full of anxiety and concern" },
    { "word": "soliloquy", "meaning": "speech you make to yourself" },
    { "word": "solvent", "meaning": "capable of meeting financial obligations" },
    { "word": "somatic", "meaning": "characteristic of the body" },
    { "word": "soporific", "meaning": "inducing sleep" },
    { "word": "sordid", "meaning": "foul and run-down" },
    { "word": "specious", "meaning": "plausible but false" },
    { "word": "spectrum", "meaning": "a broad range of related objects" },
    { "word": "spendthrift", "meaning": "someone who spends money wastefully" },
    { "word": "sporadic", "meaning": "recurring in scattered instances" },
    { "word": "squalor", "meaning": "sordid dirtiness" },
    { "word": "staccato", "meaning": "separating the notes" },
    { "word": "stanch", "meaning": "stop the flow of a liquid" },
    { "word": "stentorian", "meaning": "very loud or booming" },
    { "word": "stigma", "meaning": "a symbol of disgrace" },
    { "word": "stint", "meaning": "supply sparingly" },
    { "word": "stipulate", "meaning": "make an express demand in an agreement" },
    { "word": "stolid", "meaning": "having or revealing little emotion" },
    { "word": "stratified", "meaning": "arranged in horizontal layers" },
    { "word": "striate", "meaning": "marked with stripes" },
    { "word": "stricture", "meaning": "principle that restricts extent" },
    { "word": "strident", "meaning": "unpleasantly loud and harsh" },
    { "word": "strut", "meaning": "walk in a proud way" },
    { "word": "stultify", "meaning": "deprive of strength; make useless" },
    { "word": "stupefy", "meaning": "make someone dazed or foolish" },
    { "word": "Stygian", "meaning": "dark and dismal" },
    { "word": "subpoena", "meaning": "writ issued to compel attendance" },
    { "word": "subside", "meaning": "wear off or die down" },
    { "word": "substantiate", "meaning": "establish as with new evidence" },
    { "word": "substantive", "meaning": "having a firm basis in reality" },
    { "word": "subsume", "meaning": "contain or include" },
    { "word": "subversive", "meaning": "opposition to an established system" },
    { "word": "succor", "meaning": "assistance in difficulty" },
    { "word": "suffrage", "meaning": "legal right to vote" },
    { "word": "sundry", "meaning": "haphazard assortment of different kinds" },
    { "word": "supersede", "meaning": "take the place of" },
    { "word": "supine", "meaning": "lying face upward" },
    { "word": "supplant", "meaning": "take the place of" },
    { "word": "suppliant", "meaning": "humbly entreating" },
    { "word": "supplicant", "meaning": "someone who prays to God" },
    { "word": "supposition", "meaning": "the process of conjecturing" },
    { "word": "syllogism", "meaning": "reasoning in which a conclusion is derived from two premises" },
    { "word": "sylvan", "meaning": "relating to wooded regions" },
    { "word": "tacit", "meaning": "implied by or inferred from actions" },
    { "word": "talisman", "meaning": "a magical protection against evil" },
    { "word": "tangential", "meaning": "of superficial relevance" },
    { "word": "tautology", "meaning": "useless repetition" },
    { "word": "taxonomy", "meaning": "classification of organisms" },
    { "word": "tenet", "meaning": "a basic principle accepted as true" },
    { "word": "tenuous", "meaning": "lacking substance or significance" },
    { "word": "terrestrial", "meaning": "characteristic of the planet Earth" },
    { "word": "theocracy", "meaning": "political unit governed by a deity" },
    { "word": "thespian", "meaning": "a theatrical performer" },
    { "word": "timbre", "meaning": "distinctive property of a complex sound" },
    { "word": "tirade", "meaning": "speech of violent denunciation" },
    { "word": "toady", "meaning": "person who tries to please someone for advantage" },
    { "word": "tome", "meaning": "a large and scholarly book" },
    { "word": "torpor", "meaning": "state of motor and mental inactivity" },
    { "word": "torque", "meaning": "a twisting force" },
    { "word": "tortuous", "meaning": "marked by repeated turns and bends" },
    { "word": "tout", "meaning": "advertise in strongly positive terms" },
    { "word": "tractable", "meaning": "easily managed" },
    { "word": "transgression", "meaning": "violation of a law or duty" },
    { "word": "transient", "meaning": "lasting a very short time" },
    { "word": "translucent", "meaning": "allowing light to pass through diffusely" },
    { "word": "travail", "meaning": "use of physical or mental energy" },
    { "word": "travesty", "meaning": "composition that misrepresents a style" },
    { "word": "treatise", "meaning": "formal text treating a topic systematically" },
    { "word": "tremulous", "meaning": "quivering as from weakness" },
    { "word": "trepidation", "meaning": "feeling of alarm or dread" },
    { "word": "truculence", "meaning": "stubborn and defiant aggressiveness" },
    { "word": "tryst", "meaning": "a secret rendezvous" },
    { "word": "tumid", "meaning": "abnormally distended" },
    { "word": "turbid", "meaning": "clouded as with sediment" },
    { "word": "turgid", "meaning": "ostentatiously lofty in style" },
    { "word": "tutelary", "meaning": "providing protective supervision" },
    { "word": "uncanny", "meaning": "surpassing the ordinary or normal" },
    { "word": "undulate", "meaning": "move in a wavy pattern" },
    { "word": "unfeigned", "meaning": "not pretended; sincerely expressed" },
    { "word": "untenable", "meaning": "incapable of being defended" },
    { "word": "untoward", "meaning": "not in keeping with standards" },
    { "word": "usury", "meaning": "lending money at an exorbitant rate" },
    { "word": "vacillate", "meaning": "be undecided about something" },
    { "word": "vacuous", "meaning": "devoid of matter" },
    { "word": "valedictory", "meaning": "a farewell oration" },
    { "word": "vapid", "meaning": "lacking significance or spirit" },
    { "word": "variegated", "meaning": "having an assortment of colors" },
    { "word": "vaunt", "meaning": "show off" },
    { "word": "venal", "meaning": "capable of being corrupted" },
    { "word": "vendetta", "meaning": "a blood feud" },
    { "word": "venerate", "meaning": "regard with feelings of respect" },
    { "word": "veracious", "meaning": "habitually speaking the truth" },
    { "word": "verbose", "meaning": "using too many words" },
    { "word": "vertigo", "meaning": "a reeling sensation" },
    { "word": "vexation", "meaning": "anger produced by annoyance" },
    { "word": "viable", "meaning": "capable of normal growth" },
    { "word": "vindictive", "meaning": "disposed to seek revenge" },
    { "word": "virtuoso", "meaning": "someone dazzlingly skilled" },
    { "word": "visage", "meaning": "the human face" },
    { "word": "viscous", "meaning": "high resistance to flow" },
    { "word": "vitiate", "meaning": "make imperfect" },
    { "word": "vituperative", "meaning": "marked by harshly abusive criticism" },
    { "word": "vivisection", "meaning": "operating on living animals" },
    { "word": "vogue", "meaning": "current state of general acceptance" },
    { "word": "volatile", "meaning": "liable to lead to sudden change" },
    { "word": "vortex", "meaning": "powerful circular current of water" },
    { "word": "warrant", "meaning": "formal and explicit approval" },
    { "word": "wary", "meaning": "marked by keen caution" },
    { "word": "welter", "meaning": "confused multitude of things" },
    { "word": "whimsical", "meaning": "determined by impulse" },
    { "word": "whimsy", "meaning": "odd or fanciful idea" },
    { "word": "wistful", "meaning": "showing pensive sadness" },
    { "word": "zealot", "meaning": "fervent proponent of something" },
    { "word": "zealotry", "meaning": "fanatical devotion to a cause" }
];
