// src/lib/constants.ts

export const PLAYER_IDS = {
  Ayaan: '1d443035-34de-488f-a546-81116f0cd9a4',
  Riyaan: 'e747e862-c03f-4c3a-8631-0236c172e36c',
};

// The official Nifty 50 list as of February 2026 (51 stocks including KWIL demerger)
export const NIFTY_50_SYMBOLS = [
  "ADANIENT",
  "ADANIPORTS",
  "APOLLOHOSP",
  "ASIANPAINT",
  "AXISBANK",
  "BAJAJ-AUTO",
  "BAJAJFINSV",
  "BAJFINANCE",
  "BEL",
  "BHARTIARTL",
  "CIPLA",
  "COALINDIA",
  "DRREDDY",
  "EICHERMOT",
  "ETERNAL",
  "GRASIM",
  "HCLTECH",
  "HDFCBANK",
  "HDFCLIFE",
  "HINDALCO",
  "HINDUNILVR",
  "ICICIBANK",
  "INDIGO",
  "INFY",
  "ITC",
  "JIOFIN",
  "JSWSTEEL",
  "KOTAKBANK",
  "KWIL",
  "LT",
  "M&M",
  "MAXHEALTH",
  "MARUTI",
  "NESTLEIND",
  "NTPC",
  "ONGC",
  "POWERGRID",
  "RELIANCE",
  "SBILIFE",
  "SBIN",
  "SHRIRAMFIN",
  "SUNPHARMA",
  "TATACONSUM",
  "TATASTEEL",
  "TCS",
  "TECHM",
  "TITAN",
  "TMPV",
  "TRENT",
  "ULTRACEMCO",
  "WIPRO"
];